site_name: George 的知识库
site_author: George Cao
site_url: https://georgec6.github.io/Notes/
site_description: George's knowledge base

copyright: Copyright &copy; 2024 - 2025 <a href="https://github.com/GeorgeC6" target="_blank" rel="noopener noreferrer">George Cao</a>

theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  favicon: images/favicon.ico
  # apple-touch-icon: images/Just LOGO.png
  icon:
    logo: material/bookshelf
    repo: fontawesome/brands/github
  custom_dir: overrides
  features:
    - header.autohide # 向下滚动时自动隐藏header
    - navigation.tracking # 地址栏中的 URL 会随当前位置变化为对应小节的 URL
    - navigation.tabs
    - navigation.top
    - navigation.indexes  # 点击小节名字自动显示 index 界面
    - navigation.footer # 底部导航栏
    # - navigation.instant # 站内瞬移，但会导致公式跳转后不渲染
    - navigation.instant.progress
    - toc.integrate   # 文档 toc 集成到总目录中
    - toc.follow  # 右侧目录跟随滚动
    - search.highlight
    - search.share
    - search.suggest
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - announce.dismiss

  palette:
    - media: "(prefers-color-scheme: light)"  # 浅色模式
      scheme: default
      primary: orange
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"   # 深色模式
      scheme: slate
      primary: green
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GeorgeC6
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCq09adFYMyB4gRaUFYnVmhQ
    - icon: fontawesome/brands/soundcloud
      link: https://soundcloud.com/gorco
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/413263041
    - icon: material/forum-outline
      link: https://www.cc98.org/user/id/733259

  analytics:
    provider: google
    property: G-BKHW17C33B

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.mark:
      smart_mark: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - footnotes
  - md_in_html
  - attr_list
  - toc:
      permalink: true
      toc_depth: 4

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true # 好像能加快网页加载速度？!
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_date
  - statistics:
      page_check_metadata: comment

extra_javascript:
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js   # MathJax 3

extra_css:
  - stylesheets/extra.css
  - stylesheets/custom.css

nav:
  - 主页: "index.md"
  - 数学:
    - 微积分 I:
      - "Math/Calculus I/index.md"
    - 微积分 II: 
      - "Math/Calculus II/index.md"
      - "专题讨论": 
        - "Math/Calculus II/专题讨论/index.md"
        - "关于级数1/n^2的讨论": "Math/Calculus II/专题讨论/关于级数1:n^2的讨论.md"
    - 线性代数: "Math/Linear-Algebra/intro.md"
    - "Special Functions: From Combinatorics to Calculus":
      - "Math/Special-Functions/index.md"
      - "Week 1: Bernoulli Polynomials": "Math/Special-Functions/Week 1/index.md"
      - "Week 2: Bernoulli Numbers & Generating Function": "Math/Special-Functions/Week 2/index.md"
      - "Week 3: Taylor Polynomials & Taylor Series": "Math/Special-Functions/Week 3/index.md"
      - "Week 4: The Zeta Function": "Math/Special-Functions/Week 4/index.md"
      - "Week 5: The Gamma Function": "Math/Special-Functions/Week 5/index.md"
      - "Week 6: Convexity of Gamma Function": "Math/Special-Functions/Week 6/index.md"
      - "Week 7: Applications of Gamma Function": "Math/Special-Functions/Week 7/index.md"
      - "Week 8: Approximation of Gamma Function": "Math/Special-Functions/Week 8/index.md"
    - 概率论与数理统计:
      - "Math/Prob & Stat/index.md"
      - "杂记": 
        - "Math/Prob & Stat/Misc/index.md"
        - "协方差": "Math/Prob & Stat/Misc/Covariance.md"

  - 物理:
    - 普通物理学 I: "Physics/Physics I/intro.md"
    - 普通物理学 II: "Physics/Physics II/intro.md"
    - 原子物理:
      - "Physics/Atommechanik/index.md"
      - 课程论文: "Physics/Atommechanik/课程论文.md"
  
  - 数理方法:
    - "MathPhy/index.md"
    - "正交曲线系": "MathPhy/Curvilinear Coordinates.md"
    - 附录:
      - "MathPhy/Appendix/index.md"
      - "常用傅里叶变换/拉普拉斯变换": "MathPhy/Appendix/FT&LT.md"

  - 理论力学:
    - "TheoMech/index.md"
    - 哈密顿力学: "TheoMech/Hamilton.md"

  - CS:
    - Python: 
      - 前言: "CS/Python/intro.md"
      - 第零章 Python拾级: "CS/Python/Chapter 0.md"
      - 第一章 数据类型与运算符: "CS/Python/Chapter 1.md"
      - 第二章 常用函数: "CS/Python/Chapter 2.md"
      - 第三章 条件和循环: "CS/Python/Chapter 3.md"
      - 第四章 算法简介: "CS/Python/Chapter 4.md"
    
    - C: "CS/C/C 学习笔记.md"

    - LaTeX: 
      - "CS/LaTeX/index.md"
      - 常用符号命令: "CS/LaTeX/Symbols.md"
      - 图片排版: "CS/LaTeX/Figure.md"
      - 宏包: "CS/LaTeX/Packages.md"
      - Beamer: "CS/LaTeX/Beamer/index.md"
      - TikZ: "CS/LaTeX/TikZ/index.md"
      - 资料: "CS/LaTeX/Resources/index.md"

  - 音乐:
    - "Music/index.md"
    - "音乐理论": 
      - "Music/Music Theory/index.md"
      - "五线谱": "Music/Music Theory/SheetMusic/SheetMusic.md"
    - "音乐制作": "Music/Music Production/index.md"

  - 其它课程:
    - "Others/index.md"
    - 统计与大数据分析: 
      - "Others/Stat & Data/index.md"
      - 绪论: "Others/Stat & Data/Lec 1.md"
      - Python 基础: "Others/Stat & Data/Lec 2.1.md"
      - 样本空间与概率 Pt.I: "Others/Stat & Data/Lec 2.2.md"
      - 样本空间与概率 Pt.II: "Others/Stat & Data/Lec 3.1.md"
      - 概率论初步: "Others/Stat & Data/Lec 3.2.md"
      - 离散型随机变量: "Others/Stat & Data/Lec 4.md"
      - 连续型随机变量: "Others/Stat & Data/Lec 5.md"
      - 特殊函数及参数估计: "Others/Stat & Data/Lec 6.md"
      - 参数估计: "Others/Stat & Data/Lec 7.md"
      - 拟合优度: "Others/Stat & Data/Lec 8.md"
      - 回归分析: "Others/Stat & Data/Lec 9.md"
      - 多元回归和方差分析: "Others/Stat & Data/Lec 10.md"
      - 常见数据格式和分析: "Others/Stat & Data/Lec 11.md"
      - 机器学习 Pt.I: "Others/Stat & Data/Lec 12.md"
      - 机器学习 Pt.II: "Others/Stat & Data/Lec 13.md"
      - 机器学习 Pt.III: "Others/Stat & Data/Lec 14.md"
      - 机器学习 Pt.IV: "Others/Stat & Data/Lec 15.md"
      - 粒子物理实验中的统计学: "Others/Stat & Data/Lec 16.md"
      - Final Project: "Others/Stat & Data/Final Project/Final.md"
    - 无线网络应用:
      - "Others/无线网络应用/index.md"
      - Lec 1: "Others/无线网络应用/Lec 1.md"
      - Lec 2: "Others/无线网络应用/Lec 2.md"
      - Lec 3: "Others/无线网络应用/Lec 3.md"
      - Lec 4: "Others/无线网络应用/Lec 4.md"
      - Lec 5: "Others/无线网络应用/Lec 5.md"
      - Lec 6: "Others/无线网络应用/Lec 6.md"
      - Lec 7: "Others/无线网络应用/Lec 7.md"
      - 补充实验: "Others/无线网络应用/补充实验.md"
    - 大学物理实验: "Others/大物实验/index.md"