site_name: George 的知识库
site_author: George Cao
site_url: https://note.gorco.me/
site_description: 一名力学僧的笔记站点~

copyright: Copyright &copy; 2024 - 2025 <a href="https://github.com/GeorgeC6" target="_blank" rel="noopener noreferrer">George Cao</a>

theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  favicon: images/favicon.ico
  # apple-touch-icon: images/GeorgeSig.jpeg
  icon:
    logo: material/bookshelf
    repo: fontawesome/brands/github
  custom_dir: overrides
  features:
    # - header.autohide # 向下滚动时自动隐藏header
    - navigation.tracking # 地址栏中的 URL 会随当前位置变化为对应小节的 URL
    - navigation.tabs
    - navigation.top
    - navigation.indexes  # 点击小节名字自动显示 index 界面
    - navigation.footer # 底部导航栏
    # - navigation.instant # 站内瞬移，但会导致公式跳转后不渲染
    # - navigation.instant.progress
    - toc.integrate   # 文档 toc 集成到总目录中
    - toc.follow  # 右侧目录跟随滚动
    - search.highlight
    - search.share
    - search.suggest
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - announce.dismiss

  palette:
    - media: "(prefers-color-scheme: light)"  # 浅色模式
      scheme: default
      primary: orange
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"   # 深色模式
      scheme: slate
      primary: green
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: PT Serif Caption
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GeorgeC6
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@gorcomusic
    - icon: fontawesome/brands/soundcloud
      link: https://soundcloud.com/gorco
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/413263041
    - icon: material/forum-outline
      link: https://www.cc98.org/user/id/733259

  analytics:
    provider: google
    property: G-BKHW17C33B

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.mark:
      smart_mark: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {}
  - pymdownx.tasklist:
      custom_checkbox: true
      # clickable_checkbox: true
  - admonition
  - footnotes
  - md_in_html
  - attr_list
  - toc:
      permalink: true
      toc_depth: 4

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true # 好像能加快网页加载速度？!
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      enable_creation_date: true
      type: iso_date
      timezone: Asia/Shanghai
      exclude:
        - index.md
  - statistics:
      page_check_metadata: comment
      page_read_time: true
  - glightbox:
      effect: fade
      auto_caption: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js   # MathJax 3

extra_css:
  - stylesheets/extra.css
  - stylesheets/custom.css

nav:
  - 主页:
    - "index.md"
    - 友链: "Links.md"

  - 数学:
    - 微积分 I:
      - "Math/Calculus I/index.md"
    - 微积分 II: 
      - "Math/Calculus II/index.md"
    - 线性代数: "Math/Linear-Algebra/intro.md"
    - "Special Functions: From Combinatorics to Calculus":
      - "Math/Special-Functions/index.md"
      - "Week 1: Bernoulli Polynomials": "Math/Special-Functions/Week 1/index.md"
      - "Week 2: Bernoulli Numbers & Generating Function": "Math/Special-Functions/Week 2/index.md"
      - "Week 3: Taylor Polynomials & Taylor Series": "Math/Special-Functions/Week 3/index.md"
      - "Week 4: The Zeta Function": "Math/Special-Functions/Week 4/index.md"
      - "Week 5: The Gamma Function": "Math/Special-Functions/Week 5/index.md"
      - "Week 6: Convexity of Gamma Function": "Math/Special-Functions/Week 6/index.md"
      - "Week 7: Applications of Gamma Function": "Math/Special-Functions/Week 7/index.md"
      - "Week 8: Approximation of Gamma Function": "Math/Special-Functions/Week 8/index.md"
    - 概率论与数理统计:
      - "Math/Prob & Stat/index.md"
      - "杂记": 
        - "Math/Prob & Stat/Misc/index.md"
        - "协方差": "Math/Prob & Stat/Misc/Covariance.md"
    - 计算方法:
      - "Math/计算方法/index.md"
      - "误差": "Math/计算方法/Error.md"
      - "误差传播": "Math/计算方法/ErrorPropagation.md"
      - "线性方程组解法": "Math/计算方法/LinearEq.md"
      - "线性方程组迭代法": "Math/计算方法/LinEq(Iter).md"
      - "范数": "Math/计算方法/norm.md"
      - "共轭梯度法": "Math/计算方法/Gradient.md"
      - "特征值与特征向量": "Math/计算方法/Eigen.md"
      - "插值法": "Math/计算方法/Interpolation.md"
      - "函数逼近": "Math/计算方法/Fit.md"
      - "数值微分积分": "Math/计算方法/DerInt.md"
      - "非线性方程的解法": "Math/计算方法/NonlinearEq.md"
      - "常微分方程组数值解": "Math/计算方法/ODE.md"

  - 物理:
    - 普通物理学 I: "Physics/Physics I/intro.md"
    - 普通物理学 II: "Physics/Physics II/intro.md"
    - 原子物理:
      - "Physics/Atommechanik/index.md"
    - 计算物理:
      - "Physics/计算物理/index.md"
      - "Intro": "Physics/计算物理/Week 1/Lec00.md"
      - "Python 科学计算": "Physics/计算物理/Week 1/Lec01.md"
      - "误差分析": "Physics/计算物理/Week 2/Lec02.md"
      - "经典数值计算": "Physics/计算物理/Week 2/Lec03.md"
      - "线性代数的数值求解": "Physics/计算物理/Week 3/Lec05.md"
      - "差分法求解微分方程": "Physics/计算物理/Week 4/Lec06.md"
      - "蒙特卡洛方法": "Physics/计算物理/Week 5/Lec07.md"
      - "复杂系统中的计算方法": "Physics/计算物理/Week 6/Lec08.md"
      - "深度学习和计算物理": "Physics/计算物理/Week 8/Lec09.md"

    - 电动力学:
      - "Physics/电动力学/index.md"
      - "02-27": "Physics/电动力学/02-27.md"
      - "03-20": "Physics/电动力学/03-20.md"
    
    - 凝聚态物理专题:
      - "Physics/凝聚态物理专题/index.md"
      - "概述": "Physics/凝聚态物理专题/概述.md"
      - "超导": "Physics/凝聚态物理专题/超导.md"
      - "二维电子气": "Physics/凝聚态物理专题/二维电子气.md"
      - "低维材料": "Physics/凝聚态物理专题/低维材料.md"
      - "ARPES": "Physics/凝聚态物理专题/ARPES.md"
      - "超导量子计算": "Physics/凝聚态物理专题/超导量子计算.md"
      - "极端条件与关联电子": "Physics/凝聚态物理专题/极端条件与关联电子.md"
      - "NMR 与 muSR": "Physics/凝聚态物理专题/NMR.md"
      - "复杂系统的统计物理": "Physics/凝聚态物理专题/复杂系统的统计物理.md"
  
  - 数理方法:
    - "MathPhy/index.md"
    - "正交曲线系": "MathPhy/Curvilinear Coordinates.md"
    - "连带勒让德函数": "MathPhy/LegendreAssociated.md"
    - 附录:
      - "MathPhy/Appendix/index.md"
      - "常用傅里叶变换/拉普拉斯变换": "MathPhy/Appendix/FT&LT.md"

  - 理论力学:
    - "TheoMech/index.md"
    - 哈密顿力学: "TheoMech/Hamilton.md"

  - 材料力学:
    - "材料力学/index.md"
    - "Chapter 1: Intro": "材料力学/Chapter1/Ch1.md"
    - "Chapter 2: Tension & Compression": "材料力学/Chapter2/Ch2.md"
    - "Chapter 3: Torsion": "材料力学/Chapter3/Ch3.md"
    - "Chapter 4: Forces in Bending": "材料力学/Chapter4/Ch4.md"
    - "Chapter 5: Stresses in Bending": "材料力学/Chapter5/Ch5.md"
    - "Chapter 6: Deformations of Beams": "材料力学/Chapter6/Ch6.md"
    - "Chapter 7: Stress and Strain Analysis & Strength Theory": "材料力学/Chapter7/Ch7.md"
    - "Chapter 13: Energy Methods": "材料力学/Chapter13/Ch13.md"
    - "Chapter 10: Dynamic Loads": "材料力学/Chapter10/Ch10.md"
    - "Chapter 11: Alternating Stress": "材料力学/Chapter11/Ch11.md"
    - "Chapter 9: Stability of Columns": "材料力学/Chapter9/Ch9.md"
    - "Chapter 15: Curved Beams": "材料力学/Chapter15/Ch15.md"

  - CS:
    - "CS/index.md"
    - Python: 
      - 前言: "CS/Python/intro.md"
      - 第零章 Python拾级: "CS/Python/Chapter 0.md"
      - 第一章 数据类型与运算符: "CS/Python/Chapter 1.md"
      - 第二章 常用函数: "CS/Python/Chapter 2.md"
      - 第三章 条件和循环: "CS/Python/Chapter 3.md"
      - 第四章 算法简介: "CS/Python/Chapter 4.md"
    
    - C: "CS/C/C 学习笔记.md"

    - LaTeX: 
      - "CS/LaTeX/index.md"
      - 常用符号命令: "CS/LaTeX/Symbols.md"
      - 图片排版: "CS/LaTeX/Figure.md"
      - 表格排版: "CS/LaTeX/Table/Table.md"
      - 宏包: "CS/LaTeX/Packages.md"
      - Beamer: "CS/LaTeX/Beamer/index.md"
      - TikZ: "CS/LaTeX/TikZ/index.md"
    
    - Git: "CS/Git/git.md"

    - CS106B:
      - "CS/CS106B/index.md"
      - Lectures:
        - "Lec 0: Introduction": "CS/CS106B/Lectures/Lec 0/Intro.md"
        - "Lec 1: Functions": "CS/CS106B/Lectures/Lec 1/Functions.md"
      - Assignments:
        - A0: "CS/CS106B/Assignments/A0/a0.md"

    - FDS:
      - "CS/FDS/index.md"
      - "Introduction": "CS/FDS/Lec00.md"
      - "Algorithm Analysis": "CS/FDS/Lec01.md"
      - "Lists, Stacks, and Queues": "CS/FDS/Lec02.md"
      - "Trees": "CS/FDS/Lec03.md"
      - "Priority Queues": "CS/FDS/Lec04.md"
      - "Union-Find": "CS/FDS/Lec05.md"
      - "Graphs": "CS/FDS/Lec06.md"
      - "Sorting": "CS/FDS/Lec07.md"
      - "Hashing": "CS/FDS/Lec08.md"
      - PTA 题目摘记:
        - "CS/FDS/PTA/index.md"
        - "HW3": 
          - "Stack": "CS/FDS/PTA/HW3/Stack.md"
        - "HW4": 
          - "Tree": "CS/FDS/PTA/HW4/Tree.md"
        - "HW5":
          - "BST": "CS/FDS/PTA/HW5/BST.md"
        - "Exam":
          - "Final Exam": "CS/FDS/PTA/Exam/Final.md"

    - STM32: 
      - "CS/STM32/index.md"
      - "[1-1] STM32简介": "CS/STM32/1-1/STM32简介.md"
      - "[2-1] 第一个STM32工程": "CS/STM32/2-1/第一个工程.md"
      - "[3-1] GPIO 输出": "CS/STM32/3-1/GPIO输出.md"

    - HPC101:
      - "CS/HPC101/index.md"

  - 音乐:
    - "Music/index.md"
    - "音乐理论": 
      - "Music/Music Theory/index.md"
      - "五线谱": "Music/Music Theory/SheetMusic/SheetMusic.md"
    - "音乐制作": "Music/Music Production/index.md"

  - 其它课程:
    - "Others/index.md"
    - 统计与大数据分析: 
      - "Others/Stat & Data/index.md"
      - 绪论: "Others/Stat & Data/Lec 1.md"
      - Python 基础: "Others/Stat & Data/Lec 2.1.md"
      - 样本空间与概率 Pt.I: "Others/Stat & Data/Lec 2.2.md"
      - 样本空间与概率 Pt.II: "Others/Stat & Data/Lec 3.1.md"
      - 概率论初步: "Others/Stat & Data/Lec 3.2.md"
      - 离散型随机变量: "Others/Stat & Data/Lec 4.md"
      - 连续型随机变量: "Others/Stat & Data/Lec 5.md"
      - 特殊函数及参数估计: "Others/Stat & Data/Lec 6.md"
      - 参数估计: "Others/Stat & Data/Lec 7.md"
      - 拟合优度: "Others/Stat & Data/Lec 8.md"
      - 回归分析: "Others/Stat & Data/Lec 9.md"
      - 多元回归和方差分析: "Others/Stat & Data/Lec 10.md"
      - 常见数据格式和分析: "Others/Stat & Data/Lec 11.md"
      - 机器学习 Pt.I: "Others/Stat & Data/Lec 12.md"
      - 机器学习 Pt.II: "Others/Stat & Data/Lec 13.md"
      - 机器学习 Pt.III: "Others/Stat & Data/Lec 14.md"
      - 机器学习 Pt.IV: "Others/Stat & Data/Lec 15.md"
      - 粒子物理实验中的统计学: "Others/Stat & Data/Lec 16.md"
      - Final Project: "Others/Stat & Data/Final Project/Final.md"

    - 无线网络应用:
      - "Others/无线网络应用/index.md"
      - Lec 1: "Others/无线网络应用/Lec 1.md"
      - Lec 2: "Others/无线网络应用/Lec 2.md"
      - Lec 3: "Others/无线网络应用/Lec 3.md"
      - Lec 4: "Others/无线网络应用/Lec 4.md"
      - Lec 5: "Others/无线网络应用/Lec 5.md"
      - Lec 6: "Others/无线网络应用/Lec 6.md"
      - Lec 7: "Others/无线网络应用/Lec 7.md"
      - 补充实验: "Others/无线网络应用/补充实验.md"

    - 电工电子学及实验:
      - "Others/电工电子学及实验/index.md"
      - 课程:
        - 导论: "Others/电工电子学及实验/Lec00.md"
        - 电路基础: "Others/电工电子学及实验/Lec01.md"
        - 电路分析: "Others/电工电子学及实验/Lec02.md"
        - 分立元件基本电路: "Others/电工电子学及实验/第三章/Lec03.md"
        - 数字集成电路: "Others/电工电子学及实验/第四章/Lec04.md"
        - 集成运算放大器: "Others/电工电子学及实验/第五章/Lec05.md"
        - 波形发生和变换: "Others/电工电子学及实验/第六章/Lec06.md"
        - 功率电子电路: "Others/电工电子学及实验/第八章/Ch8.md"
        - 变压器和电动机: "Others/电工电子学及实验/第九章/Ch9.md"

    - 机械设计基础:
      - "Others/机械设计基础/index.md"
      - "Lec 1: Introduction": "Others/机械设计基础/Lec01.md"
      - "Chapter 2: 联接": "Others/机械设计基础/Ch2.md"
      - "Chapter 6: 蜗轮蜗杆传动": "Others/机械设计基础/Ch6/Ch6.md"
      - "Chapter 7: 轮系": "Others/机械设计基础/Ch7/Ch7.md"
    - 创业基础: "Others/创业基础.md"